# Generated by Django 3.0.3 on 2021-04-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210409_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='State_Medical_Council',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
