# Generated by Django 3.0.3 on 2021-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210409_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedies',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/images'),
        ),
    ]
