# Generated by Django 3.1.5 on 2021-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210409_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalmap',
            field=models.CharField(default='', max_length=500),
        ),
    ]
